### ISSUE TITLE
Cannot fix manyToMany relations cases

### ISSUE THREAD

**Issue by thomasavada** [good-vision-slovakia/strapi-connector-bookshelf#3]
For those who found this solution for Strapi 3.6.9 or below but seems not to work with your manyToMany relations, well here is the solution

## Solution

- Clone a copy of this package, or fork.
- Change `["belongsToMany", "manyWay"]` to `["belongsToMany", "manyWay", "manyToMany"]` in the source code, all 3 places. 

After that, it should be working fine. 

By the way, thank you for this solution. We all appreciate it.

**Comment by adrianplavka** [comment]
Hello,

thank you for your solution! I've pushed it to the master.
